
SELECT
    MST.POL_CD,
    CN.CNTR_TYPE,
    COUNT(CN.CNTR_NO) AS CNTR_COUNT,
    SUM(CN.CNTR_WGT) AS TOTAL_WGT
FROM FMS_HBL_MST MST
JOIN FMS_HBL_CNTR CN
ON  MST.HBL_NO = CN.HBL_NO
WHERE MST.ETD BETWEEN '20250501' AND '20250511'
GROUP BY MST.POL_CD, CN.CNTR_TYPE
ORDER BY MST.POL_CD, CN.CNTR_TYPE;
