
SELECT CN.HBL_NO,COUNT(CN.CNTR_NO) AS CNTR_COUNT,MST.ETD
FROM FMS_HBL_CNTR CN JOIN FMS_HBL_MST MST
ON CN.HBL_NO = MST.HBL_NO
GROUP BY CN.HBL_NO, MST.ETD
ORDER BY COUNT(CN.CNTR_NO) DESC, MST.ETD ASC
FETCH FIRST 1 ROWS ONLY;
